name: continious delivery

on:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: checkout do codigo
        uses: actions/checkout@v4

      - name: compactar arquivos com tar
        run: |
          tar -cvf projeto.tar main.py requirements.txt README.md tests/

      - name: fazer upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: projeto-tar
          path: projeto.tar
          if-no-files-found: error      
          overwrite: true                

  deploy:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - name: baixar artefato do job delivery
        uses: actions/download-artifact@v4
        with:
          name: projeto-tar
          path: ./deploy-artifact

      - name: listar conteudo compactado
        run: ls -R ./deploy-artifact

      - name: descompactar artefato
        run: tar -xvf ./deploy-artifact/projeto.tar -C ./deploy-artifact

      - name: listar conteudo final
        run: ls -R ./deploy-artifact
