name: continious delivery

on:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: checkout do codigo
        uses: actions/checkout@v4

      - name: compactar arquivos com zip
        run: |
          zip -r projeto.zip main.py requirements.txt README.md tests/

      - name: fazer upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: projeto-zip
          path: projeto.zip
          if-no-files-found: error      
          overwrite: true                

  deploy:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - name: baixar artefato do job delivery
        uses: actions/download-artifact@v4
        with:
          name: projeto-zip
          path: ./deploy-artifact

      - name: listar conteudo compactado
        run: ls -R ./deploy-artifact

      - name: descompactar artefato
        run: unzip ./deploy-artifact/projeto.zip -d ./deploy-artifact

      - name: listar conteudo final
        run: ls -R ./deploy-artifact

  docker:
      runs-on: ubuntu-latest
      needs: deploy
      steps:
        - name: Checkout do codigo
          uses: actions/checkout@v4

        - name: Set up QEMU 
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login no DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build e push da imagem Docker
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/conversor-moedas:latest
