name: CI Conversor De Moedas Simples

on:
  pull_request:
    branches:
      - main

jobs:
  executar-testes:
    name: Testes com Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest requests

      - name: Analise com Flake8
        run: flake8 .

      - name: Executar testes com Pytest
        run: PYTHONPATH=. pytest tests/

  qualidade-pr:
    name: Regras de qualidade para Pull Requests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Aplicar regras de qualidade ao PR
        uses: spiceai/pulls-with-spice-action@v1
        with:
          require_title_min_length: '10'
          require_description_min_length: '20'
          required_labels_any: 'bug,feature'
          required_issue_types: 'bug,enhancement'
          enforce_draft: 'false'
          custom_error_messages: >
            {
              "title_too_short": "Melhorar o título",
              "description_too_short": "Adicione uma descrição mais detalhada.",
              "missing_any_labels": "Escolha pelo menos um label",
              "invalid_issue_type": "Adicione o tipo da issue no título ou descrição (ex: bug: conserta erro na conversão)."
            }
