# continuous integration conversor de moedas simples
name: CI Conversor De Moedas Simples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

#permissão para upload SARIF 
permissions:
  contents: read
  security-events: write

jobs:
  executar-testes:
    runs-on: ubuntu-latest

    steps:
      - name: Executar testes com Pytest
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar pacotes e dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest requests

      - name: Analisar código Flake8
        run: flake8 .

      - name: Executar testes com Pytest
        run: PYTHONPATH=. pytest tests/

# analisar o codigo com Pylint e com code scanning.
  analisar-codigo:
    name: Analise de Codigo com Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Instalar dependencias Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Executar Pylint e gerar relatorio SARIF
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint

# notificação de sucesso no discord
  discord-success:
    needs: [executar-testes, analisar-codigo]    # só roda se todos jobs obter sucesso
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Notificar sucesso no Discord
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub Actions Bot
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          color: "#00ff00"
          message: |
            Continuous Integration executado com sucesso!!!
            Repositório: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Autor: ${{ github.actor }}
            Commit: ${{ github.event.head_commit.message }}

# notificação de falha no discord
  discord-failure:
    needs: [executar-testes, analisar-codigo]  # só roda se alguns jobs tiver falhar
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Notificar falha no Discord
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          username: GitHub Actions Bot
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png 
          color: "#ff0000"
          message: |
            Continuous Integration falhou!!!
            Repositório: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Autor: ${{ github.actor }}
            Commit: ${{ github.event.head_commit.message }}
